### ISSUE TITLE
Remove 'direction' keyword from neumann boundary conditions

### ISSUE THREAD

**Issue by VikingScientist** [OPM/IFEM#14]
Neumann boundary conditions comes in two types. Either you have the exact solution, or you specify some fluxes/tractions.

**Poisson**
Exact solution available: You want to specify [du/dx, du/dy, du/dz] and have IFEM treat this appropriately. Input vector functions
Heat flux: You want to specify du/dn as some flux into/out of your domain. Input scalar functions

**Elasticity**
Exact solution available: You want to specify the stresses: sigma and have IFEM dot this with the normal vector. Input tensor functions.
Tractions: You want to specify sigma*n=[fx,fy,fz] as some directional forces on your boundary. Input vector functions.

Proposed solution:
Count the number of components (for instance pipe | symbols) specified by the user in the input file neumann tag and treat it as either pre-multiplied with the normal vector, or post-multiplied with it. For scalar equations one can have vector or scalar neumann conditions. For vector equations one can have tensor or vector neumann conditions.

Remove the 'direction' keyword altogether.

**Comment by timovanopstal** [comment]
In essence you suggest two things?
1. Adding functionality by supporting supplying the full gradient/stress i.e. before dotting with n, in the case you have an exact solution (or in some case where it is easier to find a stress tensor which does the right thing, than cutting up the boundary and specifying tractions on all of these). I can see the point of this... but should switching between these two modes be based on grepping for |? That seems a bit more bug-prone and less readable to me than an extra attribute.
2. Removing flexibility by always assume you want to specify normal fluxes/tractions. I can't fully support removing this flexibility, for our apps now it may work, but I recall that there are cases where the natural boundary conditions involve tangents, s.a. Maxwell. But how about letting the normal direction be the default (if not already the case)?

**Comment by VikingScientist** [comment]
What I want is to be able to specify neumann conditions with or without dotted by the normal vector.

To answer the other things you address:
1. Grepping for | might not be optimal, and I am open for other suggestions such as providing a keyword. The current way is specifying a 'direction' keyword which is at best confusing, and at worst misleading and a source of bugs. It is a magic parameter which could be zero, positive or negative with different behaviour in each case. There are two acceptable neumann conditions and two only. These are pre-dotted with n and post-dotted with n.

2. The neumann conditions come from integration by parts, changing volume derivatives to surface fluxes. I don't see how this results in tangential terms. Could you provide a detailed example of any tangential neumann terms?

**Comment by timovanopstal** [comment]
Ok, direction usage may not be very intuitive, and if/how the stuff read in at `SIMbase::parseBCTag` is used, is up to the app/integrand. I guess I would be OK with a cleanup of this interface. Could you clarify what you mean by pre/post-dotted? I guess you mean whether you are supplying the actual Neumann flux, or want IFEM to dot with n? On second thoughts, as far as more exotic boundary conditions go, I guess that is up to the app to parse, not SIMbase. But if you are interested in examples of what I was referring to, check Ern & Guermond's book §4.1, where n x g type fluxes appear from rewriting the Laplacian as curl curl u + ... and such.

**Comment by kmokstad** [comment]
Closing this over three-year-old discussion now:
* The "direction" attribute is needed or at least convenient. It defines the direction of the applied traction vector on the boundary; 0 means in the direction of the outward-directed normal vector (this is the default), a value larger than 0 means in that particular global coordinate direction, a negative values means that the traction components are defined directly. This is now also documented in the wiki-pages.
* When you have the exact solution (anasol), you don't need to define the actual traction components, as in that case they are computed directly from the provided stress tensor (for flux vector in case of scalar equation).
