### ISSUE TITLE
Move the wiki onto trunk

### ISSUE THREAD

**Issue by VikingScientist** [OPM/IFEM#146]
The wiki already publicly available at [https://github.com/akva2/IFEM/wiki](https://github.com/akva2/IFEM/wiki), and it is more than good enough to put up here.

**Comment by akva2** [comment]
wiki has been copied, but i have not migrated the images yet.

**Comment by akva2** [comment]
i suggest we stick the images it the wiki git, even though images and git is evil.

the wiki files are in the git 
git clone https://github.com/OPM/IFEM.wiki

**Comment by VikingScientist** [comment]
Moved all images to the wiki-page here. Also updated the 3D-primitives illustration which was wrong. This should close this issue.
