### ISSUE TITLE
Update wiki with include & partitioning tags

### ISSUE THREAD

**Issue by VikingScientist** [OPM/IFEM#192]
Useful things missing from the wiki documentation:

`<partitioning procs="4" nperproc="1"/>`

`<include>some-shared-xinp-file.xinp</include>`

probably more, but these are the ones I learned about in the last few days

**Comment by VikingScientist** [comment]
Also `<variables>` is another undocumented feature that would benefit from some love at the wiki pages

**Comment by akva2** [comment]
anasol page added, https://github.com/OPM/IFEM/wiki/The--anasol--context
partitioning shorthand added, https://github.com/OPM/IFEM/wiki/Parallel-computations
include added, https://github.com/OPM/IFEM/wiki/General-input-format
