### ISSUE TITLE
Bug in matrix or vector dump

### ISSUE THREAD

**Issue by TheBB** [OPM/IFEM#299]
Reproducing files here: https://gist.github.com/TheBB/33cc23e2d6127bcb15fae21c5a2f5daf. There are four: `02.lr`, `03.lr`, `snapshot.xinp` and `test.py`.

It's a simple beam elasticity case that I run with:

    LinEl snapshot.xinp -2D -LR

Then the dumped matrices are checked with the `test.py` script. Run with both `02.lr` and `03.lr` as mesh. The residual for the finer mesh will be much higher, even though the solutions themselves look identical. I'm wondering why that is. These are two meshes out of a chain of increasing resolution, and it's definitely not a gradual change, there's something about `03.lr` and above have that `02.lr` and below don't have.

My output:

* `02.lr`: Residual norm: 1.1185073313739549e-11
* `03.lr`: Residual norm: 0.2923536476758355

cc @VikingScientist (could be something wrong with the lr-file perhaps)

**Comment by akva2** [comment]
i can reproduce. the problem is related to neumann conditions, not to LR (i can reproduce with two tensor meshes as well).

**Comment by VikingScientist** [comment]
Can reproduce. The following tensor product xinp file will create residual of 0.29

``` xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>                        
                                                                               
<simulation>                                                                   
                                                                               
  <geometry dim="2" Lx="10" Ly="1">                                               
    <raiseorder patch="1" u="0" v="1"/>                                        
    <refine     patch="1" u="159" v="15"/>                                     
    <topologysets>                                                                
      <set name="fixed" type="edge"><item patch="1">1</item></set>                
      <set name="right" type="edge"><item patch="1">2</item></set>                
    </topologysets>                                                               
  </geometry>                                                                     
                                                                                  
  <boundaryconditions>                                                            
    <dirichlet set="fixed" comp="12"/>                                            
    <neumann set="right" direction="2">2.5</neumann>                              
  </boundaryconditions>                                                           
                                                                                  
  <postprocessing>                                                                
    <dump_lhs_matrix format="m">snapshot.mx</dump_lhs_matrix>                     
    <dump_rhs_vector format="m">snapshot.rhs</dump_rhs_vector>                    
    <dump_sol_vector format="m">snapshot.sol</dump_sol_vector>                    
  </postprocessing>                                                               
                                                                                  
  <elasticity>                                                                    
    <isotropic E="150000.0" nu="0.25"/>                                           
  </elasticity>                                                                   
                                                                                  
</simulation>                                                                     
```

**Comment by kmokstad** [comment]
Just a hunch if it appears with Neumann conditons only: It can be due to the "partikulærløsning". Såkalte S0-krefter, som ikke inngår i høyresiden men må tas hensyn til hvis man skal evaluere løsningen i vilkårlige punkt i elementet.

Sorry for the language switch. At least I don't think it has to do with the matrix dump as such, as the title indicate.

Will check it over the weekend.

**Comment by kmokstad** [comment]
BTW: Can the same effect be provoked for s scalar problem, i.e., Poisson, or is it Elasticity-only? Then it may be easier to trace.

**Comment by akva2** [comment]
i cannot reproduce for poisson.

**Comment by kmokstad** [comment]
I think the reason for this is the way we handle the Dirichlet boundary conditions; These DOFs are condensed out from the global system matrices, such that the matrices that are dumped from the `solveSystem` method lacks the contributions from these DOFs. Therefore, we cannot compute the residual in this way (`A*x - R`) from these matrices. We lack the contributions from the reaction forces in the fixed DOFs. These forces can be calculated on the element level (as `R_i = k_ij*v_j` for each fixed DOF `i`) and assembled after we have solved the linear system (this is dealt with in OPM/IFEM-Elasticity#39) as a separate assembly step. In the nonlinear solvers we have the option to include this already (calculated during the tangent+residual assembly in the subsequent iteration).

**Comment by TheBB** [comment]
Ok, looks like this is just an insufficient `eps`. Sorry for the alarm.

Thanks @akva2 for pointing that out.

**Comment by kmokstad** [comment]
yes, with `eps=0.0` on all the `dmp_*_*` tags the test.py script also yields O(1e-11) residual.
The default value is 1.0e-6.
