### ISSUE TITLE
UMFPACK mode does not work with multiple right-hand-sides

### ISSUE THREAD

**Issue by kmokstad** [OPM/IFEM#386]
With #385 I also include the option to use UMFPACK in place of SuperLU in the L2-projection, motivated by the fact that SuperLU decides to produce NaN results (or core dump) instead of returning an error state when something is wrong with the coefficient matrix. However, with UMFAPCK I only got the first stress component out when projecting the stress tensor, all the others were zero! Probably an error in our UMFPACK wrapping. Guess that package itself is supposed to manage multiple RHSs.

**Comment by akva2** [comment]
They specifically point out only one rhs in the umfpack docmentation so we need to handle this ourself.
