### ISSUE TITLE
TestNonLinSIM.SingleDOF broken in master?

### ISSUE THREAD

**Issue by timovanopstal** [OPM/IFEM#95]
I only trigger this in Release mode on my OSX (i.e. with clang?) Problem traced back to 85a70245010e0829fa4fabae0ead1b502c5ced13

**Comment by timovanopstal** [comment]
what goes wrong is:
`ASSERT_EQ(solver.solveStep(tp),SIM::CONVERGED);`
triggers an abort trap

**Comment by kmokstad** [comment]
That must be some clang/Mac specific problem, so ASSERT_EQ cannot compare two enum values?

**Comment by kmokstad** [comment]
Try if the following resolves the issue:
+++ b/src/SIM/SIMbase.C
@@ -983,8 +983,8 @@ void SIMbase::printSolutionSummary (const Vector& solution, int printSol,
 {
   // Compute and print solution norms
   const size_t nf = this->getNoFields(1);
-  size_t iMax[nf];
-  double dMax[nf];
+  size_t iMax[nf > 0 ? nf : nsd];
+  double dMax[nf > 0 ? nf : nsd];

**Comment by kmokstad** [comment]
The proposed fix did the matter. Resolved by 4e8fa1ede4e05acc29293d4f45db7aaeef58618b
